package anasin;

import java.awt.Toolkit;
import java.io.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.StringReader;
import java_cup.runtime.Symbol;

/**
 *
 * @author Emmanuel David Ventura Silva
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    Color c = new Color(192,192,192);
    
    public Inicio() {
        initComponents(); 
        this.getContentPane().setBackground(c);
        this.setLocationRelativeTo(null);
        setIcon();
    }
    
    private void lexico() {
        int i = 0;
        
        File file = new File("texto.txt");
        PrintWriter escribir;
        
        aEntrada.setText(tCadena.getText());
        
        try {
            escribir = new PrintWriter(file);
            escribir.print(tCadena.getText());
            escribir.close();
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }

        try {
            Reader lector = new BufferedReader(new FileReader("texto.txt"));
            Lexer lexer = new Lexer(lector);
            String salida = "";
            
            while (true) {
                i++;
                Tokens tokens = lexer.yylex();
                if (tokens == null) {
                    aSalida.setText(salida);
                    return;
                }
                switch (tokens) {
                    case NO_DEFINIDO:
                        salida += "Token ("+ i + "): " + tokens + "\n";
                        break;
                    case IDENTIFICADOR:
                        salida += "Token ("+ i + "): "+ lexer.lexema + ": " + tokens + "\n";
                        break;
                    case NUMERO:
                        salida += "Token ("+ i + "): "+ lexer.lexema + ": " + tokens + "\n";
                        break;
                    case OR:
                        salida += "Token ("+ i + "): |" + ": " + tokens + "\n";
                        break;
                    case AND:
                        salida += "Token ("+ i + "): &" + ": " + tokens + "\n";
                        break;
                    case NOT:
                        salida += "Token ("+ i + "): !" + ": " + tokens + "\n";
                        break;
                    case IGUAL:
                        salida += "Token ("+ i + "): =" + ": " + tokens + "\n";
                        break;
                    case SEPARADOR:
                        salida += "Token ("+ i + "): ;" + ": " + tokens + "\n";
                        break;
                }
            }
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }
    
    public void sintaxis(){
        String cadena = tCadena.getText();
        Sintax s = new Sintax(new anasin.LexCup(new StringReader(cadena)));
        
        try {
            s.parse();
            aSalida.append("Sin errores de sintaxis");
            aSalida.setForeground(new Color(128, 255, 0));
        } catch (Exception ex) {
            ex.getStackTrace();
            Symbol sym = s.getS();
            aSalida.append("Error de sintaxis. Línea: " + (sym.right + 1) + " Columna: " + (sym.left + 1) + ", Texto: \"" + sym.value + "\"");
            aSalida.setForeground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tCadena = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bAnalizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aEntrada = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        aSalida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Sintáctico");
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        tCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCadenaActionPerformed(evt);
            }
        });

        jLabel1.setText("Texto");

        bAnalizar.setText("Analizar");
        bAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnalizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Texto ingresado:");

        jLabel3.setText("Analisis");

        aEntrada.setEditable(false);
        aEntrada.setColumns(20);
        aEntrada.setRows(5);
        jScrollPane1.setViewportView(aEntrada);

        aSalida.setEditable(false);
        aSalida.setColumns(20);
        aSalida.setRows(5);
        jScrollPane3.setViewportView(aSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAnalizar)
                        .addGap(342, 342, 342))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)))
                        .addGap(86, 86, 86)
                        .addComponent(tCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addComponent(tCadena, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bAnalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnalizarActionPerformed
        if(tCadena.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "INSERTA TEXTO", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else{
            lexico();
            sintaxis();
            tCadena.setText("");
        }
    }//GEN-LAST:event_bAnalizarActionPerformed

    private void tCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCadenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("uno.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aEntrada;
    private javax.swing.JTextArea aSalida;
    private javax.swing.JButton bAnalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField tCadena;
    // End of variables declaration//GEN-END:variables
}
